# istio-rbac-productage.yaml
# get permission only to product page
# user is *, this need to be configure in real life 
# update may take several minutes for apply to be effectif
# apply RBAC of Backend also 
# ---
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRole
metadata:
   name: productpage-viewer
   namespace: default
spec : 
  rules: 
  - services: ["productpage.default.svc.cluster.local"]
  methods: ["GET"]
# ----
apiVersion: "config.istio.io/v1alpha2"
kind: ServiceRoleBinding
metadata:
  name: bind-productpage-viewer
  namespace: default
spec: 
  subjects:
  - user: "*"
  roleRef:
  kind: ServiceRole
  name: "productpage-viewer"
